apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE SCHEMA IF NOT EXISTS  desafio;

    CREATE  TABLE IF NOT EXISTS desafio.users (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    email VARCHAR(50) NOT NULL,
    birthdate VARCHAR(255) NOT NULL,  
    PRIMARY KEY (`id`)
    );
    
    INSERT INTO `desafio`.`users` (`name`, `last_name`, `cpf`, `email`, `birthdate`) VALUES ('John', 'Doe', '12345678987', 'johndoe@gmail.com', '1985-11-19');
    INSERT INTO `desafio`.`users` (`name`, `last_name`, `cpf`, `email`, `birthdate`) VALUES ('Maria', 'Joana', '2334656787823', 'mariaj@gmail.com', '1987-11-19');

   