apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: janotijr/desafio:v3
          resources:
            limits:
              cpu: "1"
              memory: "100Mi"
            requests:
              cpu: "0.5"
              memory: "30Mi"
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: db-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: database
